name = "gemini-worker"
main = "workers/gemini-worker.js"
compatibility_date = "2024-01-01"

[vars]
ENDPOINTS_GEMINI = "https://generativelanguage.googleapis.com/v1alpha/models/gemini-2.0-flash-exp"
ENDPOINTS_YOUTUBE = "https://youtube.googleapis.com/youtube/v3"
ENDPOINTS_MAPS = "https://maps.googleapis.com/maps/api"
# R2_PUBLIC_URL = "https://pub-xxx.r2.dev"  # 替换为你的 R2 公共访问 URL

# KV 绑定
[[kv_namespaces]]
binding = "TRAVEL_DATA"
id = "a12b9591362449f693a97bfa59e9847d"

# D1 数据库绑定

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "travel-data"
database_id = "5bd81e9a-d0ad-4fe6-a5c8-dce03ccb0266"

# R2 存储桶绑定
[[r2_buckets]]
binding = "TRAVEL_IMAGES"
bucket_name = "travel-images"
preview_bucket_name = "travel-images-dev"
