export const provinces = [
  { code: 'BJ', name: '北京' },
  { code: 'TJ', name: '天津' },
  { code: 'HE', name: '河北' },
  { code: 'SX', name: '山西' },
  { code: 'NM', name: '内蒙古' },
  { code: 'LN', name: '辽宁' },
  { code: 'JL', name: '吉林' },
  { code: 'HL', name: '黑龙江' },
  { code: 'SH', name: '上海' },
  { code: 'JS', name: '江苏' },
  { code: 'ZJ', name: '浙江' },
  { code: 'AH', name: '安徽' },
  { code: 'FJ', name: '福建' },
  { code: 'JX', name: '江西' },
  { code: 'SD', name: '山东' },
  { code: 'HA', name: '河南' },
  { code: 'HB', name: '湖北' },
  { code: 'HN', name: '湖南' },
  { code: 'GD', name: '广东' },
  { code: 'GX', name: '广西' },
  { code: 'HI', name: '海南' },
  { code: 'CQ', name: '重庆' },
  { code: 'SC', name: '四川' },
  { code: 'GZ', name: '贵州' },
  { code: 'YN', name: '云南' },
  { code: 'XZ', name: '西藏' },
  { code: 'SN', name: '陕西' },
  { code: 'GS', name: '甘肃' },
  { code: 'QH', name: '青海' },
  { code: 'NX', name: '宁夏' },
  { code: 'XJ', name: '新疆' },
  { code: 'TW', name: '台湾' },
  { code: 'HK', name: '香港' },
  { code: 'MO', name: '澳门' }
]

export const countries = [
  { code: 'US', name: '美国' },
  { code: 'GB', name: '英国' },
  { code: 'FR', name: '法国' },
  { code: 'DE', name: '德国' },
  { code: 'IT', name: '意大利' },
  { code: 'ES', name: '西班牙' },
  { code: 'CA', name: '加拿大' },
  { code: 'AU', name: '澳大利亚' },
  { code: 'JP', name: '日本' },
  { code: 'KR', name: '韩国' },
  // ... 可以继续添加更多国家
] 